version: '3'

services:
  minecraft:
    image: maximilianschneider/mcs
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      CONSOLE: "true"
    restart: always

volumes:
  mc:
  rcon:
